import { Translations } from './types';

// Using the standard export URL with a GID parameter for reliability
export const SHEET_URL = 'https://docs.google.com/spreadsheets/d/1L_U_qYZirPKWzAr5M6OFCf84A2sWaWphYvEsHMySo-w/export?format=csv&gid=0';

export const TRANSLATIONS: Translations = {
  title: '2026 农历新年歌曲浏览',
  subtitle: '马来西亚 YouTube 新年歌集锦',
  totalVideos: '新年歌总数',
  totalViews: '总浏览量',
  totalLikes: '总点赞数',
  totalComments: '总评论数',
  avgViewsPerDay: '日均浏览量',
  prevMonth: '上个月',
  nextMonth: '下个月',
  monday: '一',
  tuesday: '二',
  wednesday: '三',
  thursday: '四',
  friday: '五',
  saturday: '六',
  sunday: '日',
  close: '关闭',
  playOnYoutube: '在 YouTube 播放',
  publishedOn: '发布于',
  by: '作者',
  noVideos: '今日无发布视频',
  january: '一月',
  february: '二月',
  march: '三月',
  april: '四月',
  may: '月',
  june: '六月',
  july: '七月',
  august: '八月',
  september: '九月',
  october: '十月',
  november: '十一月',
  december: '十二月',
  loading: '正在获取新年歌数据...',
  videos: '首新年歌曲发布',
  showMore: 'View More',
  showLess: 'View Less',
  festiveTitle: '新年歌曲发布日历',
  rankingSectionTitle: '新年歌风云榜',
  topTotalViews: '总浏览量',
  topDailyViews: '日均增量',
  mostLiked: '最多点赞',
  mostRecent: '最新发布',
  oldest: '最早发布',
  viewRankLabel: '总浏览量排名'
};